### ISSUE TITLE
Came across an error

### ISSUE THREAD

**Issue by RushilJalal** [Chinchilla15/cv-app#1]
![image](https://github.com/Chinchilla15/cv-app/assets/54212357/6acd6ba8-8efe-4777-8ad9-cd2022db12f4)

**Comment by Chinchilla15** [comment]
Thank you for bringing this issue to my attention! I tried to add the Vercel Speed Insights for my app but for some reason it did not work, I forgot to push the changes with the dependencies removed. Just pushed changes to main. Thanks
